name: 领取美团外卖红包

# doc https://docs.github.com/en/actions/reference/events-that-trigger-workflows

on:
  push:
    branches:
      - main
  # 每天 11:30
  schedule:
    - cron: '05 11 * * *'

jobs:
  start:
    name: grab coupon
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Run app
        run: yarn install
      - run: yarn start
        env:
          TOKEN: ${{ secrets.TOKEN }}
          BARK_KEY: ${{ secrets.BARK_KEY }}
          SEND_KEY: ${{ secrets.SEND_KEY }}
